# Harmony Jekyll theme general configurations

# Base URL
baseurl: ''

# Site live URL
url: http://patolivre.tk

# Localhost
# url: http://127.0.0.1:4000

# Harmony theme configuration. Please change accordingly.
harmony:
  name: PatoLivre Hacker Club
  #inserir image na pasta assets/img
  image_top: logo.png
  # Little description about your site
  description:  PatoLivre Hacker Club
  # 'meta_description:' Write an awesome description for your new site here.
  # It will appear in your document head meta (for Google search results) and
  # in your feed.xml site description.
  meta_description: PatoLivre Hacker Club
  basetheme: theme-base-01 # pre defined thmes are darken, blue-water, redish.
  author: # Author details
    name: PatoLivre
    email: patolivre@googlegroups.com
    url: http://patolivre.github.io

  # Google Analytics key, leave blank to ignore
  # google_analytics_key: UA-xxxx-x

  # Profile links, leave blank to ignore
  social:
    github: patolivre
    twitter: grupopatolivre
    facebook: grupopatolivre
    # gplus: +patolivre
  # Toggle disclaimer in footer
  show_disclaimer: true

# Conversion / Build settings
markdown:    kramdown
# This is how you put pygments config in jekyll 2.0 instead of pygments: true
highlighter: pygments

# Permalinks
permalink:        pretty

exclude:
  - CNAME
  - Gemfile
  - Rakefile
  - README.md
  - .gitignore
  - .sass-cache
  - Gemfile.lock

# Sass conversion configs
sass:
    sass_dir: assets/css/_sass
    style: :compressed
